### PR TITLE
added dark mode #36

### PR DESCRIPTION
**Pull request by dcharles525**
The colors may need some tweaking, and there is a weird bar at the top after toggling the theme, but goes away after restart, might need some guidance there @parnold-x

### CODE REVIEW

**Comment by dcharles525** [comment]
Screenshot from 2019-05-05 11 04 45
Screenshot from 2019-05-05 11 05 08

**Comment by AKDub** [comment]
Is there a way for me to update/install this on my system manually? I have enable dark mode system wide which messed up NaSC, and your update looks great.

**Comment by dcharles525** [comment]
@AKDub yes just clone this branch and follow the build instructions in the Readme.

**Comment by parnold-x** [comment]
Thank you for the contribution. I am not in favor of a toggle in the app. 
Also I think there are two styles needed because the style changes in this branch make the contrast for the light theme worse.
I think I will support dark mode when elementary launches its prefer dark setting with this style for dark.
https://blog.elementary.io/the-need-for-a-freedesktop-dark-style-preference/

**Comment by parnold-x** [comment]
Dark mode is implemented now

**Pull request closed without merging**
