### PR TITLE
Fixed installation of libqalculatenasc.so (again)

### PR DESCRIPTION
**Pull request by Mailaender**
The same fix from https://github.com/parnold-x/nasc/pull/47 after it regressed in https://github.com/parnold-x/nasc/pull/56.

### CODE REVIEW

**Comment by Mailaender** [comment]
See https://build.opensuse.org/package/show/X11:Pantheon/nasc for an integration test.

**Comment by parnold-x** [comment]
Hi. I reverted it because it doesn't build with that on launchpad and locally here. I not really know cmake so don't know why.

**Comment by Mailaender** [comment]
Try to build with `cmake -DCMAKE_INSTALL_LIBDIR=/usr/lib` then, but I guess Ubuntu has it's own set of macros which take care of that automatically.

**Comment by Mailaender** [comment]
Alternatively use https://cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html

**Comment by parnold-x** [comment]
It builds with that locally. Great. But still there is the problem with launchpad.

**Comment by phw** [comment]
For launchpad something like this in `debian/rules` could fix it:

    override_dh_auto_configure:
    	dh_auto_configure -- -DCMAKE_INSTALL_LIBDIR=/usr/lib

**Comment by parnold-x** [comment]
@phw Thanks a lot. Will try this.

**Comment by nick87720z** [comment]
Hello, again right this bug (or almost this). CMAKE_INSTALL_LIBDIR doesn't work.
Right after configuration i can open build/libqalculatenasc/cmake_install.cmake and see this:
```
$ grep -nRF '${CMAKE_INSTALL_PREFIX}/lib'
libqalculatenasc/cmake_install.cmake:36:  if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libqalculatenasc.so" AND
libqalculatenasc/cmake_install.cmake:37:     NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libqalculatenasc.so")
libqalculatenasc/cmake_install.cmake:39:         FILE "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libqalculatenasc.so"
libqalculatenasc/cmake_install.cmake:42:  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE SHARED_LIBRARY FILES "/home/nick87720z/dist/nasc/build/libqalculatenasc/libqalculatenasc.so")
libqalculatenasc/cmake_install.cmake:43:  if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libqalculatenasc.so" AND
libqalculatenasc/cmake_install.cmake:44:     NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libqalculatenasc.so")
libqalculatenasc/cmake_install.cmake:46:      execute_process(COMMAND "/usr/bin/strip" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libqalculatenasc.so")
```
Looking to ccmake, LIB_SUFFIX=64 and CMAKE_INSTALL_LIBDIR=lib64.
I can't find, from where it goes.

**Pull request merged**
