### PR TITLE
Build libqalculatenasc with CMake, other fixes

### LINKED ISSUE #85: Build libqalculatenasc with CMake
The current libqualculatenasc build is incompatible with CMake's Ninja backend:

```
ninja: error: 'libqalculatenasc.so', needed by 'nasc', missing and no known rule to make it
```

Plus, it uses a `libtool` generated for Linux, does not use pkg-config to find libqualculate itself, does not use the same compiler as CMake…

I just wrote a FreeBSD port that installs NaSC, and I had to include this patch:

```diff
--- libqalculatenasc/Makefile.in.orig   2017-09-28 09:09:25 UTC
+++ libqalculatenasc/Makefile.in
@@ -1,8 +1,6 @@
-CC = g++
-LIBTOOL = ./libtool
+CC? = c++
 DEBUG = -g
 CFLAGS = -std=c++11 -fPIC -O3 -c $(DEBUG)
-LFLAGS = --tag=CXX --mode=link g++ -shared

 BINDIR=@exedir@
 MANDIR=@mandir@
@@ -10,16 +8,16 @@ LIBDIR=@libdir@
 INCDIR=@prefix@/include/

 libqalculatenasc.so : QalculateNasc.o
-       $(LIBTOOL) $(LFLAGS) QalculateNasc.o -o libqalculatenasc.so -lqalculate
+       $(CC) -shared QalculateNasc.o -o libqalculatenasc.so `pkg-config --libs libqalculate`

 QalculateNasc.o : QalculateNasc.h QalculateNasc.cc
-       $(CC) $(CFLAGS) QalculateNasc.cc
+       $(CC) $(CFLAGS) QalculateNasc.cc `pkg-config --cflags libqalculate`

 all: libqalculatenasc.so

 clean:
        \rm -f QalculateNasc.o libqalculatenasc.so

-install:
+install: libqalculatenasc.so
        install libqalculatenasc.so $(LIBDIR)
        install QalculateNasc.h $(LIBDIR)
```

Everything works fine without libtool! So I don't see a reason why this thing is not just built inside CMake.

### PR DESCRIPTION
**Pull request by myfreeweb**
Fixes #85 and some deprecation warnings, adds gitignore

### CODE REVIEW

**Comment by parnold-x** [comment]
Hey, thank you for the PR.
I tried to compile it but it says:

> make
Scanning dependencies of target qalculatenasc
[  5%] Building CXX object libqalculatenasc/CMakeFiles/qalculatenasc.dir/QalculateNasc.cc.o
In file included from /usr/include/c++/5/thread:35:0,
                 from /home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc:5:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^
/home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc:8:6: error: ‘shared_ptr’ in namespace ‘std’ does not name a template type
 std::shared_ptr<Calculator> calc;
      ^
/home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc: In function ‘void new_calculator()’:
/home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc:15:9: error: ‘calc’ was not declared in this scope
         calc = std::shared_ptr<Calculator> (new Calculator() );
         ^
/home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc:15:16: error: ‘shared_ptr’ is not a member of ‘std’
         calc = std::shared_ptr<Calculator> (new Calculator() );
                ^
/home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc:15:42: error: expected primary-expression before ‘>’ token
         calc = std::shared_ptr<Calculator> (new Calculator() );
                                          ^
/home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc: In function ‘void load_currencies()’:
/home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc:22:9: error: ‘calc’ was not declared in this scope
         calc->loadGlobalCurrencies();
         ^
/home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc: In function ‘int get_function_size()’:
/home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc:27:16: error: ‘calc’ was not declared in this scope
         return calc->functions.size();
                ^
/home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc: In function ‘int get_variable_size()’:
/home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc:31:16: error: ‘calc’ was not declared in this scope
         return calc->variables.size();
                ^
/home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc: In function ‘char* get_function_name(int)’:
/home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc:35:13: error: ‘calc’ was not declared in this scope
         if (calc->functions[index]->isActive() ) {
             ^
/home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc: In function ‘char* get_function_description(int)’:
/home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc:46:13: error: ‘calc’ was not declared in this scope
         if (calc->functions[index]->isActive() ) {
             ^
/home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc: In function ‘char* get_function_category(int)’:
/home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc:56:13: error: ‘calc’ was not declared in this scope
         if (calc->functions[index]->isActive() ) {
             ^
/home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc: In function ‘char* get_function_title(int)’:
/home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc:66:13: error: ‘calc’ was not declared in this scope
         if (calc->functions[index]->isActive() ) {
             ^
/home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc: In function ‘char* get_function_arguments(int)’:
/home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc:76:13: error: ‘calc’ was not declared in this scope
         if (calc->functions[index]->isActive() ) {
             ^
/home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc: In function ‘char* get_function_arguments_list(int)’:
/home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc:97:13: error: ‘calc’ was not declared in this scope
         if (calc->functions[index]->isActive() ) {
             ^
/home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc: In function ‘char* get_variable_name(int)’:
/home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc:123:13: error: ‘calc’ was not declared in this scope
         if (calc->variables[index]->isActive() ) {
             ^
/home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc: In function ‘char* get_variable_category(int)’:
/home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc:134:13: error: ‘calc’ was not declared in this scope
         if (calc->variables[index]->isActive() ) {
             ^
/home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc: In function ‘char* get_variable_title(int)’:
/home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc:143:13: error: ‘calc’ was not declared in this scope
         if (calc->variables[index]->isActive() ) {
             ^
/home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc: In function ‘char* Calculator_calculate_store_variable(const char*, const char*)’:
/home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc:178:39: error: ‘nullptr’ was not declared in this scope
             KnownVariable *variable = nullptr;
                                       ^
/home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc:179:17: error: ‘calc’ was not declared in this scope
             if (calc->variableNameTaken (var, variable) ) {
                 ^
/home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc: In function ‘void clear_variables()’:
/home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc:197:9: error: ‘calc’ was not declared in this scope
         calc->resetVariables();
         ^
/home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc: In function ‘void abortt()’:
/home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc:201:9: error: ‘calc’ was not declared in this scope
         calc->abort();
         ^
/home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc: In function ‘void delete_calculator()’:
/home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc:205:9: error: ‘calc’ was not declared in this scope
         calc.reset();
         ^
/home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc: In function ‘int busy()’:
/home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc:209:13: error: ‘calc’ was not declared in this scope
         if (calc->busy () )
             ^
/home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc: In function ‘char* get_exchange_rates_url()’:
/home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc:216:32: error: ‘calc’ was not declared in this scope
         return convert_string (calc->getExchangeRatesUrl () );
                                ^
/home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc: In function ‘char* get_exchange_rates_filename()’:
/home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc:220:32: error: ‘calc’ was not declared in this scope
         return convert_string (calc->getExchangeRatesFileName () );
                                ^
/home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc: In function ‘std::__cxx11::string intern_calc_wait(std::__cxx11::string)’:
/home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc:231:12: error: ‘calc’ was not declared in this scope
     while (calc->busy() ) {
            ^
/home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc:232:14: error: ‘std::chrono’ has not been declared
         std::chrono::milliseconds duration (10);
              ^
/home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc:233:14: error: ‘std::this_thread’ has not been declared
         std::this_thread::sleep_for (duration);
              ^
/home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc:233:38: error: ‘duration’ was not declared in this scope
         std::this_thread::sleep_for (duration);
                                      ^
/home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc: In function ‘std::__cxx11::string intern_calc_terminate(std::__cxx11::string)’:
/home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc:239:9: error: ‘calc’ was not declared in this scope
     if (calc->busy() ) {
         ^
/home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc: In function ‘std::__cxx11::string intern_calc(std::__cxx11::string)’:
/home/pa/Projekte/test/nasc/libqalculatenasc/QalculateNasc.cc:247:5: error: ‘calc’ was not declared in this scope
     calc->beginTemporaryStopMessages();
     ^
libqalculatenasc/CMakeFiles/qalculatenasc.dir/build.make:62: die Regel für Ziel „libqalculatenasc/CMakeFiles/qalculatenasc.dir/QalculateNasc.cc.o“ scheiterte
make[2]: *** [libqalculatenasc/CMakeFiles/qalculatenasc.dir/QalculateNasc.cc.o] Fehler 1
CMakeFiles/Makefile2:154: die Regel für Ziel „libqalculatenasc/CMakeFiles/qalculatenasc.dir/all“ scheiterte
make[1]: *** [libqalculatenasc/CMakeFiles/qalculatenasc.dir/all] Fehler 2
Makefile:127: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 2

**Comment by myfreeweb** [comment]
oops, sorry, forgot the C++11 flag (my compiler defaults to C++17, so I didn't notice)

**Comment by parnold-x** [comment]
Now the c stuff compiles. Very cool. Can you just revert the search.forward2 change in Inputview. This is since 3.22 and nasc is targeting 3.18 right now.

**Comment by myfreeweb** [comment]
Sure.

**Comment by parnold-x** [comment]
Thanks a lot

**Pull request merged**
