### PR TITLE
don't build libqalculatenasc shared library, but link directly

### LINKED ISSUE #81: install libqalculatenasc.so to a private lib directory
Currently, the private and unversioned libqalculatenasc.so shared library is installed directly to LIBDIR, where ldconfig would pick it up as a public shared library.

Please install it into a private LIBDIR subdirectory (for example, LIBDIR/qalculatenasc/libqalculatenasc.so).

### PR DESCRIPTION
**Pull request by decathorpe**
Fixes #81

### CODE REVIEW

**Comment by decathorpe** [comment]
Please check if it breaks anything when building nasc on ubuntu/elementary, I've only tested it on fedora.

**Comment by parnold-x** [comment]
Ok today I tested it on Juno and it breaks stuff on elementary. It's something with a DS0 symbol I can't figure out.

**Comment by decathorpe** [comment]
I have no idea what might cause this. The build also fails on fedora 27, but succeeds on fedora 28, with the same version of CMake. Honestly, CMake is just bad, I'd port this to meson, it might be faster than trying to debug CMake issues. (If you want, I can submit a pull request for a meson port.)

**Comment by parnold-x** [comment]
Yeah meson would be way better. I hope I find some time in the future for this.

**Comment by decathorpe** [comment]
I've done a preliminary port in a fork, but it's hitting the same error on fedora 27 as before (unresolved symbol, missing DSO on command line). So I think this isnt a CMake / meson issue, but a bug in an older version of `ld` or something.

**Pull request merged**
